### ISSUE TITLE
Questions about the compressed file

### ISSUE THREAD

**Issue by ivanperez-keera** [datalad/git-remote-rclone#4]
Hi

The documentation says that:

> At the remote end, git-remote-rclone maintains a directory with two files:
> 
> - refs: a small text file listing the refs provided by the remote
> - repo.7z: a 7-Zip archive of a bare Git repository

Does that imply that, if you are working with a git repo that is 3GB, you are going to have an extra local copy that is 3GB large (assuming it cannot be compressed much)?

**Comment by yarikoptic** [comment]
Yes, but having 3gb .git/objects is a stretch on its own. Use git-annex with or without datalad to manage large files and keep your git small

**Comment by ivanperez-keera** [comment]
Oh I have an 18GB repo filled with relatively small files (<5MB) that change often. Git-annex is not something I'd want to use in that case.

Anyway, thanks for answering!

**Comment by yarikoptic** [comment]
> Oh I have an 18GB repo filled with relatively small files (<5MB) that change often. Git-annex is not something I'd want to use in that case.

FWIW:
Since they change often, especially if they are binary, you definitely do not want to use git to store them natively -- you would need to "fetch" all prior versions with every `git clone`.
IMHO git-annex might still be the solution for you.  With ~3,000-5,000 files you have you would still have a nicely performing git repository with quite small `.git/objects` and could then share it on github etc, or anywhere rclone supports via this git transfer protocol, while uploading actual load using git-annex.

**Comment by mih** [comment]
FTR: My largest N of a dataset used in practice is around 500k annexed files, all less than 1MB.
